# Generated by Django 4.0.4 on 2022-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no_of_rooms', models.IntegerField()),
                ('address', models.TextField()),
                ('number_of_staffs', models.CharField(max_length=100)),
                ('services', models.TextField()),
            ],
        ),
    ]
